package com.system.po;

public class Note {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.noteID
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    private Integer noteid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.teacherID
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    private Integer teacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.url
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.title
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.teacherName
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    private String teachername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.release
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    private String release;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column note.content
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.noteID
     *
     * @return the value of note.noteID
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public Integer getNoteid() {
        return noteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.noteID
     *
     * @param noteid the value for note.noteID
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public void setNoteid(Integer noteid) {
        this.noteid = noteid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.teacherID
     *
     * @return the value of note.teacherID
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.teacherID
     *
     * @param teacherid the value for note.teacherID
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.url
     *
     * @return the value of note.url
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.url
     *
     * @param url the value for note.url
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.title
     *
     * @return the value of note.title
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.title
     *
     * @param title the value for note.title
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.teacherName
     *
     * @return the value of note.teacherName
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public String getTeachername() {
        return teachername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.teacherName
     *
     * @param teachername the value for note.teacherName
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public void setTeachername(String teachername) {
        this.teachername = teachername == null ? null : teachername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.release
     *
     * @return the value of note.release
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public String getRelease() {
        return release;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.release
     *
     * @param release the value for note.release
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public void setRelease(String release) {
        this.release = release == null ? null : release.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column note.content
     *
     * @return the value of note.content
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column note.content
     *
     * @param content the value for note.content
     *
     * @mbg.generated Tue Jan 02 02:54:36 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}